services:
  - type: web
    name: abb-timeline
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PERSISTENT_DATA_DIR
        value: /var/data
    disk:
      name: abb-timeline-data
      mountPath: /var/data
      sizeGB: 1
